name: My First Setup

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run lint:fix
      - run: npm run build --if-present
      - name: Check if build directory exists
        run: |
          if [ ! -d "./build" ]; then
            echo "Build directory does not exist. Exiting."
            exit 1
          fi
      - name: Set up Git Remote URL
        run: |
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
      - name: Pull latest changes
        run: |
          git pull --tags origin main
      - name: Deploy with gh-pages
        run: |
          npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
